/**
 * @fileoverview Public entry point for the reliability marketplace package.
 * The domain types file (types.ts) is frozen after the per-role fault
 * change. Lane owners request further type changes through a separate
 * small PR, never inside a lane PR.
 */

export type {
  Entity,
  EntityRole,
  JsonValue,
  KycStatus,
  KycTier,
  Listing,
  MarketplaceTransaction,
  Outcome,
  OutcomeFault,
  OutcomeState,
  Receipt,
  ReliabilityCategory,
  ReliabilityEvent,
  ReliabilityOutcome,
  ReliabilityState,
  ScoreView,
  TermsDecision,
  TermsOffer,
  TermsReasonCode,
  TermsVersion,
  TransactionParticipant,
  TransactionType,
  VerificationMethod,
} from './types';
export {
  BETA_SCORING_VERSION,
  BetaScoringPolicy,
  DEFAULT_BETA_SCORING_PARAMS,
  STUB_SCORING_VERSION,
  stubInitialState,
  StubScoringPolicy,
  type BaseEventWeight,
  type BetaScoringParams,
  type ScoringPolicy,
  type WeightReason,
} from './scoring';
export {betaCdf, betaQuantile, logGamma} from './beta-math';
export {
  checkKyc,
  KYC_GATE_VERSION,
  type KycGateCode,
  type KycGateResult,
  type KycGateSubject,
} from './kyc-gate';
export {
  basisPointsOf,
  FEE_CHARGE_VERSION,
  quoteFeeCharge,
  settleFeeCharge,
  toMinorUnits,
  type FeeCharge,
  type FeeChargeSide,
  type FeeChargeStatus,
} from './fee-charges';
export {
  decideOffer,
  effectiveOfferStatus,
  OFFER_STATUSES,
  OfferError,
  type Offer,
  type OfferStatus,
} from './offers';
export {
  composeEventWeight,
  weightInputsKey,
  type EventWeightRecord,
} from './event-weights';
export {
  DEFAULT_PAIR_DECAY_PARAMS,
  HYPERBOLIC_PAIR_DECAY_VERSION,
  HyperbolicPairDecay,
  pairKeyFor,
  STUB_PAIR_DECAY_VERSION,
  StubPairDecay,
  type HyperbolicPairDecayParams,
  type PairDecay,
  type PairDirection,
} from './pair-decay';
export {
  CURVE_FEE_TERMS_VERSION,
  CurveFeeTermsPolicy,
  DEFAULT_CURVE_FEE_TERMS_PARAMS,
  feeBpsFor,
  STUB_FEE_TERMS_VERSION,
  StubFeeTermsPolicy,
  type CurveFeeTermsParams,
  type FeeCurveSide,
  type FeeTermsPolicy,
  type TermsPolicyInput,
} from './fees-policy';
export {
  DELIVERY_TIER_VERIFICATION,
  DELIVERY_TIERS,
  EscrowTransactionLifecycle,
  LIFECYCLE_NEXT_STAGES,
  LIFECYCLE_VERSION,
  LifecycleError,
  RESOLVER_CONFIDENCE,
  VOLUNTARY_REFUND_CONFIDENCE,
  type DeliveryTier,
  type DisputeDecision,
  type FundEscrowInput,
  type LifecycleStage,
  type LifecycleStore,
  type LifecycleTransition,
  type OpenDisputeInput,
  type OpenTransactionInput,
  type RefundEscrowInput,
  type ReleaseEscrowInput,
  type ResolveDisputeInput,
  type StoredLifecycleTransition,
  type TransactionLifecycle,
} from './lifecycle';
export {
  flowLifecycleOutcome,
  type LifecycleFlowHistory,
  type LifecycleFlowResult,
} from './lifecycle-flow';
export type {
  EscrowFundRequest,
  EscrowPort,
  EscrowRefundResult,
  EscrowReleaseResult,
  EscrowSession,
} from './escrow-port';
export type {
  DealFundingRequest,
  OmnibusBalance,
  OmnibusFundingStore,
  PaperDealFundingPort,
  PaperDealFundingRecord,
  PaperOmnibusPool,
  PaperPoolDeposit,
  PaperPoolTransfer,
} from './omnibus-funding';
export {
  INVOICE_EVIDENCE_VERSION,
  INVOICE_TERMS_SCHEMA,
  InvoiceEvidenceError,
  invoiceDeadline,
  invoiceOutcome,
  invoiceTermsHash,
  STUB_PAYMENT_EVIDENCE_VERSION,
  hashInvoiceTerms,
  StubPaymentEvidenceProducer,
  validateInvoiceTerms,
  type InvoiceSettlement,
  type InvoiceTerms,
  type PaymentEvidenceProducer,
  type PaymentVerificationInput,
} from './evidence-payment';
export {
  checkDeliveryAgainstTerms,
  DELIVERY_TERMS_CHECK_VERSION,
  type DeliveryTermsCheck,
  type DeliveryTermsViolation,
} from './evidence-delivery';
export {
  DEMO_KYC_SCRIPTS,
  KYC_BADGES,
  KYC_CHECK,
  KYC_HOWS,
  KYC_RE_REGISTRATION_SIGNALS,
  KYC_TIER_RULES,
  MOCK_KYC_PROVIDER_NAME,
  MockKycProvider,
  countsAsVerified,
  tierForSubmittedChecks,
  type KycBadge,
  type KycCheckInput,
  type KycFlowErrorCode,
  type KycHow,
  type KycPolicyInput,
  type KycProfile,
  type KycProvider,
  type KycRecordStore,
  type KycReRegistration,
  type KycResult,
  type KycScript,
  type KycStatusRecord,
  type KycSubjectKind,
  type KycTierRules,
  type KycVendorDecision,
  type KycView,
  type MockKycOptions,
  type RegisterEntityInput,
  KycFlowError,
} from './kyc';
export {
  applyEventsToStates,
  categoryForType,
  outcomeToEvents,
  refreshTermsDecisions,
} from './event-flow';
export {
  FARM_OUTCOMES,
  FARM_TRANSACTIONS,
  FIXTURE_ENTITIES,
  KYC_FIXTURE_CASES,
  FIXTURE_LISTINGS,
  FIXTURE_OUTCOMES,
  FIXTURE_STATES,
  FIXTURE_TRANSACTIONS,
  OUTCOME_BUYER_FAULT,
  OUTCOME_INVOICE,
  OUTCOME_NO_FAULT,
  OUTCOME_SELLER_FAULT,
  OUTCOME_SERVICE,
  TX_INVOICE,
  TX_SERVICE,
  type KycFixtureCase,
} from './fixtures/index';
